### ISSUE TITLE
/ir_rx/acquire.py "list index out of range".

### ISSUE THREAD

**Issue by water5** [peterhinch/micropython_ir#10]
I use /ir_rx/acquire.py receive several IR remote controllers via below:

```python
from ir_rx.acquire import *
ira = IR_GET(Pin(23, Pin.IN))
ira.acquire()
```
Most IR remote controllers acquire success, but one of IR remote controller cause error below:

> 000  2428
>
> Traceback (most recent call last):
>  File "/lib/ir_rx/acquire.py", line 47, in decode
>IndexError: list index out of range
>Traceback (most recent call last):
>  File "stdin", line 1, in "module"
>  File "/lib/ir_rx/acquire.py", line 91, in acquire

**Comment by peterhinch** [comment]
In the docs I warn that `acquire` is for experimenters: one reason is that it's impossible for me to diagnose errors when they occur with a remote I don't possess. I'm sorry but I really can't figure out how to progress this one.
